services:
  ##################################
  # CLOUDFLARE TUNNEL
  ##################################
  cloudflared-comfyui:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TOKEN}
    restart: unless-stopped
    network_mode: "host"  # ✅ Allow direct access to your Mac's local network
    environment:
      - TUNNEL_URL=http://localhost:8188  # ✅ Forward Cloudflare Tunnel to your local ComfyUI
